name: Update Module Name

on:
  push:
    branches:
      - main
    paths:
      - 'go.mod'

jobs:
  update-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update go.mod
        run: |
          sed -i 's/module github.com\/placeholder\/repo/module github.com\/${{ github.repository_owner }}\/${{ github.event.repository.name }}/' go.mod

      - name: Commit and Push
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add go.mod
          git commit -m "Update go.mod with correct module path"
          git push
